#!/bin/bash
#PBS -q home
#PBS -N snATAC_pre
#PBS -l nodes=1:ppn=1
#PBS -l walltime=48:00:00
#PBS -o /home/zhc268/logs/snATAC_pre.o
#PBS -e /home/zhc268/logs/snATAC_pre.e
#PBS -V
#PBS -M zhangc518@gmail.com
#PBS -m abe
#PBS -A epigen-group

export PATH=$PATH:/home/zhc268/data/software/snATAC_qc/

fastqdir="/projects/ps-epigen/seqdata/"
i1=${fastqdir}I1.fastq.gz
i2=${fastqdir}I2.fastq.gz
r1=${fastqdir}R1.fastq.gz
r2=${fastqdir}R2.fastq.gz
l=/home/zhc268/data/software/snATAC_qc/barcodes/barcodes.txt


snATAC_preprocess.py --i1 $i1 --i2 $i2 --r1 $r1 --r2 $r2 --s1 XW_71 --s2 XW_72 -l $l -o $fastqdir

